fix ci lint

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -34,8 +34,12 @@ jobs:
       - run:
           name: Lint
           command: |
-            gofmt -l .
-            test -z $(gofmt -l .)
+            bad_files=$(gofmt -l . | (grep -v ^vendor/ || :))
+            if [[ "${bad_files}" != "" ]]; then
+              echo "Lint failed on the following files:"
+              echo ${bad_files}
+              exit 1
+            fi
 
   build:
     <<: *defaults
